apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  creationTimestamp: null
  name: {{.Release.Name}}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{.Values.istio.host}}
    port:
      name: httpcolor
      number: 80
      protocol: HTTP