apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: {{.Release.Name}}
spec:
  gateways:
  - {{.Release.Name}}
  hosts:
  - {{.Values.istio.host}}
  http:
  - route:
    {{ $local := . }}
    {{- range $index, $track := .Values.deployment }}
    - destination:
        host: {{$local.Release.Name}}-{{$track.image.version}}
        port:
          number: 80
      weight: {{$track.image.weight}}
    {{ end }}