version: '1.0'
stages:
- Deploy
steps:
  BuildingDockerImage:
    title: Building Docker Image
    type: build
    image_name: todaywasawesome/colorcoded
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
    dockerfile: Dockerfile
  IstioInfo:
    title: Gather istio information
    image: containers101/k8sclitoolset
    commands:
    - kubectl config use-context ${{KUBE_CONTEXT}}
    - cf_export canaryVersion=${{RELEASE}}-${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
    - cf_export canaryImage=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
  DeployHelm:
    title: Prod with Canary Helm Release
    image: containers101/k8sclitoolset
    stage: Deploy
    commands:
    - helm upgrade --install ${{RELEASE}} deploy/helm/colors --namespace=${{NAMESPACE}} --debug --set deployment[0].track=release --set deployment[0].image.repository=r.cfcr.io/todaywasawesome/todaywasawesome/colorcoded --set deployment[0].image.tag="${{canaryImage}}" --set deployment[0].image.version="${{canaryVersion}}" --set deployment[0].image.pullSecret="codefresh-generated-r.cfcr.io-cfcr-${{NAMESPACE}}"