version: '1.0'
stages:
- Deploy
steps:
  BuildingDockerImage:
    title: Building Docker Image
    type: build
    image_name: todaywasawesome/colorcoded
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
    dockerfile: Dockerfile
  blueGreenDeploy:
    title: "Blue/Green Rollout"
    image: codefresh/k8s-blue-green:master
    stage: Deploy
    environment:
      - SERVICE_NAME=color-app
      - DEPLOYMENT_NAME=color-app
      - NEW_VERSION=${{CF_SHORT_REVISION}}
      - HEALTH_SECONDS=30
      - NAMESPACE=bluegreen
      - KUBE_CONTEXT=canary@FirstKubernetes