apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: color-app
    version: 00baseline00
  name: color-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: color-app
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: color-app
    spec:
      containers:
      - image: docker.io/containers101/color-coded:master
        imagePullPolicy: Always
        name: color-app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 40
