apiVersion: v1
kind: Service
metadata:
  name: color-app
spec:
  ports:
  - name: http1
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: color-app
    version: 00baseline00
  sessionAffinity: None
  type: LoadBalancer