apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue
  name: blue

spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue

  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: blue
        
    spec:
      containers:
      - env:
        - name: COLOR
          value: '#44B3C2'
        image: containers101/color-coded:master
        imagePullPolicy: Always
        name: blue
        ports:
        - containerPort: 8080
          protocol: TCP

        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
