apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: blue
    io.codefresh.account.name: todaywasawesome
    io.codefresh.scm.branch: {{CF_BRANCH}}
    io.codefresh.scm.revision: {{CF_REVISION}}
  name: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - env:
        - name: COLOR
          value: '#44B3C2'
        - name: blank
          value: blank
        image: r.cfcr.io/todaywasawesome/todaywasawesome/color-coded:{{CF_REVISION}}
        imagePullPolicy: Always
        name: blue
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: codefresh-generated-r.cfcr.io-cfcr-myapp  
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 40
